development:
  adapter: postgresql
  database: search_development
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: search_production
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: search_development
  host: localhost
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: search_test
  host: localhost
  pool: 5
  timeout: 5000

